dbt_reference_project:
  outputs:
    dev:
      type: duckdb
      path: ../database.duckdb
      threads: 4
      attach:
        - path: "../raw_files/raw_files_database.duckdb"
          type: duckdb
          alias: raw_files_database
  target: dev
